### ISSUE TITLE
Example code

### ISSUE THREAD

**Issue by FrozenDroid** [thejpster/nrfxlib-sys#3]
Hi, is there any chance you could upload an example on how to use this? I tried to use it, but it would give me a SIGTRAP. Are there any interrupt handlers I need to define, etc?

**Comment by thejpster** [comment]
I have a demo project, but I'm waiting on permission to publish it.

Yes, you need to define EGU and IPC interrupt handlers which call functions of the appropriate name defined in the static lib. You also need to supply some libc functions, but I find linking libc doesn't work because it clashes with compiler builtins. I wrote tinyrlibc to avoid this, but it's not the best solution.

**Comment by FrozenDroid** [comment]
What does your memory.x look like?
Whatever I do, I keep getting 
```
Program received signal SIGTRAP, Trace/breakpoint trap.
0xeffffffe in ?? ()
```

**Comment by FrozenDroid** [comment]
@thejpster Are you still waiting for permission? I'm dying to play with the board in Rust but can't get any further :(

**Comment by FrozenDroid** [comment]
I managed to get it to run just fine :) I was just missing the SPM part.
Only thing I'm having problems with, that probably aren't related to this crate, is using `nrf_getaddrinfo`... whatever I do, I keep getting `EINVAL` as error...

**Comment by thejpster** [comment]
Yeah, we're almost there! There's an example of doing DNS lookups and TLS connections coming too.

**Comment by jonathanpallant** [comment]
Have a look at https://github.com/42-technology-ltd
